version: "1"
services:
  receiver:
    image: receiver
    container_name: receiver
    build: 
      context: receiver-container/
    depends_on:
      - filter

  filter:
    image: filter
    container_name: filter
    build: 
      context: filter-container/
    expose:
      - “8010”
    depends_on:
      - process

  process:
    image: process
    container_name: process
    build: 
      context: process-container/
    expose:
      - “8020"



